import PDFDocument from "pdfkit";
import nodemailer from "nodemailer";

export const handleChatbotRequest = async (req, res) => {
  const { question, email } = req.body;

  if (!question || !email) {
    return res.status(400).json({ message: "Topic and Email are required." });
  }

  try {
    // 1. DIRECT API CALL (Targets v1 Stable to avoid 404 errors)
    const API_KEY = process.env.GEMINI_API_KEY;
    const GEMINI_URL = `https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=${API_KEY}`;
    const aiResponse = await fetch(GEMINI_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{ 
          parts: [{ 
            text: `Explain "${question}" for a student. Use clear headings, bullet points, and a detailed summary. Keep it professional.` 
          }] 
        }]
      })
    });

    const data = await aiResponse.json();

    if (!aiResponse.ok) {
      throw new Error(data.error?.message || "Gemini API Error");
    }

    const text = data.candidates[0].content.parts[0].text;

    // 2. PDF GENERATION WITH STYLING
    const doc = new PDFDocument({ margin: 50, bufferPages: true });
    let buffers = [];
    doc.on('data', (chunk) => buffers.push(chunk));
    
    doc.on('end', async () => {
      const pdfBuffer = Buffer.concat(buffers);

      // 3. EMAIL LOGIC
      const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
          user: process.env.EMAIL_USER,
          pass: process.env.EMAIL_PASS, 
        },
      });

      const mailOptions = {
        from: `"ReadMe AI Assistant" <${process.env.EMAIL_USER}>`,
        to: email,
        subject: `Study Guide: ${question}`,
        text: `Hello! Your AI-generated study guide for "${question}" is ready and attached.`,
        attachments: [{
            filename: `${question.replace(/\s+/g, '_')}_Guide.pdf`,
            content: pdfBuffer,
        }],
      };

      await transporter.sendMail(mailOptions);
      return res.status(200).json({ message: "PDF Sent Successfully!" });
    });

    // --- PDF CONTENT DESIGN ---
    
    // Header
    doc.fillColor("#035DCA").fontSize(26).text("ReadMe AI Assistant", { align: "center" });
    doc.moveDown(0.5);
    doc.fillColor("#64748b").fontSize(10).text("Personalized Study Document", { align: "center" });
    
    doc.moveDown(2);
    doc.strokeColor("#e2e8f0").lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(2);

    // Title
    doc.fillColor("#1e293b").fontSize(20).text(question, { underline: true });
    doc.moveDown();

    // Body Text
    doc.fillColor("#334155").fontSize(12).text(text, {
      lineGap: 5,
      paragraphGap: 10,
      align: 'justify'
    });

    // Add Footer to all pages
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc.fillColor("#94a3b8").fontSize(8)
         .text(
           "Generated by ReadMe AI Assistant • For Educational Purposes Only", 
           50, 
           doc.page.height - 50, 
           { align: "center" }
         );
    }

    doc.end();

  } catch (error) {
    console.error("❌ Chatbot Error:", error.message);
    res.status(500).json({ message: "Service Error", error: error.message });
  }
};